version: '3.8'

services:
  app:
    build: .
    container_name: rxflow_app
    ports:
      - "8080:80"
    volumes:
      - ./src:/var/www/html
      - ./logs:/var/log/rxflow
      - ./data:/data
    environment:
      - PHP_MEMORY_LIMIT=512M
    depends_on:
      - redis
      - mysql

  mysql:
    image: mysql:8.0
    container_name: rxflow_mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"

  redis:
    image: redis:alpine
    container_name: rxflow_redis
    ports:
      - "6379:6379"

  worker:
    build: .
    container_name: rxflow_worker
    command: php /var/www/html/workers/queue_worker.php
    volumes:
      - ./src:/var/www/html
      - ./logs:/var/log/rxflow
    depends_on:
      - redis

volumes:
  mysql_data: